### ISSUE TITLE
Configuration values defined below [planterbox-summary] block do not load.

### ISSUE THREAD

**Issue by wholewheattoast** [npilon/planterbox#7]
In refactoring some cfg's I happened to move the position of 
```
[planterbox-summary]
always-on = True
```
 
From the bottom of a config file closer to top.

All config values below it are not loaded.

Able to verify by running nose2 with `-D` and self["some_expected_value"] not being defined.

Is this expected behavior?

**Comment by npilon** [comment]
Yes; these are config file header sections, and their placement in the file alters the context of other statements following them.
